service: bonzai
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:PROFILE}
  region: eu-north-1
  iam:
    role: ${env:LAMBDA_ROLE}
  deploymentMethod: direct

useDotenv: true

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  getBookings:
    handler: functions/getBookings/index.handler
    events:
    - httpApi:
        path: '/api/booking'
        method: GET
  postBooking:
    handler: functions/postBooking/index.handler
    events:
    - httpApi:
        path: '/api/booking'
        method: POST
  updateBooking:
    handler: functions/updateBooking/index.handler
    events:
    - httpApi:
        path: '/api/booking'
        method: PUT
  deleteBooking:
    handler: functions/deleteBooking/index.handler
    events:
    - httpApi:
        path: '/api/booking'
        method: DELETE

resources:
    Resources: 
        roomsDb:
            Type: AWS::DynamoDB::Table
            Properties: 
                TableName: rooms
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST